steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'backend'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'backend'
    args: ['run', 'build']

  # Deploy Frontend (static hosting via Cloud Run)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'portfolio-frontend',
      '--source=frontend',
      '--region=us-central1',
      '--allow-unauthenticated'
    ]

  # Deploy Backend (API)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'portfolio-backend',
      '--source=backend',
      '--region=us-central1',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
