export const favoriteBooks = [
  {
    title: 'AI 2041: Ten Visions for Our Future',
    author: 'Kai-Fu Lee',
    genre: 'Technology',
    image: 'https://m.media-amazon.com/images/I/615OLCyQllL._AC_UY218_.jpg',
    url: 'https://amzn.to/4rVgVF9',
  },
  {
    title: 'Horus Rising',
    author: 'Dan Abnett',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/51tfGLC+L-L._SY300_.jpg',
    url: 'https://amzn.to/4pM5bTV',
  },
  {
    title: 'Legion',
    author: 'Dan Abnett',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/51rF8vr6c1L._SY300_.jpg',
    url: 'https://amzn.to/44GFFae',
  },
  {
    title: 'A Thousand Sons',
    author: 'Graham McNeill',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/51TA5VOF8kL._SY300_.jpg',
    url: 'https://amzn.to/4selMS4',
  },
  {
    title: 'The First Heretic',
    author: 'Aaron Dembski-Bowden',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/51CCBuvt3JL._SY300_.jpg',
    url: 'https://amzn.to/3MPviuy',
  },
  {
    title: 'Know No Fear',
    author: 'Dan Abnett',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/61CFnPa7H6L._SY300_.jpg',
    url: 'https://amzn.to/4pQXRqc',
  },
  {
    title: 'Fear to Tread',
    author: 'James Swallow',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/51tTk4gEntL._SY300_.jpg',
    url: 'https://amzn.to/3KTFtOd',
  },
  {
    title: 'Angel Exterminatus',
    author: 'Graham McNeill',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/51t-jMP2B8L._SY300_.jpg',
    url: 'https://amzn.to/45jlQ92',
  },
  {
    title: 'Betrayer',
    author: 'Aaron Dembski-Bowden',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/51ID5NfJM3L._SY300_.jpg',
    url: 'https://amzn.to/4p8bUGy',
  },
  {
    title: 'The Unremembered Empire',
    author: 'Dan Abnett',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/51p00xwkoZL._SY300_.jpg',
    url: 'https://amzn.to/3NbUdbL',
  },
  {
    title: 'The Master of Mankind',
    author: 'Aaron Dembski-Bowden',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/51u4XUPNHyL._SY300_.jpg',
    url: 'https://amzn.to/3Ya8bgL',
  },
  {
    title: "Ender's Game",
    author: 'Orson Scott Card',
    genre: 'Science Fiction',
    image: 'https://m.media-amazon.com/images/I/91P0lfcIEJS._AC_UY218_.jpg',
    url: 'https://amzn.to/4pCkKxz',
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    image: 'https://m.media-amazon.com/images/I/81TZj+3ecWL._AC_UY218_.jpg',
    url: 'https://amzn.to/3KJaK6q',
  },
  {
    title: 'A Game of Thrones',
    author: 'George R.R. Martin',
    genre: 'Fantasy',
    image: 'https://m.media-amazon.com/images/I/71Jzezm8CBL._AC_UY218_.jpg',
    url: 'https://amzn.to/4aaAxyE',
  },
  {
    title: 'Berserk, Vol. 1',
    author: 'Kentaro Miura',
    genre: 'Manga',
    image: 'https://m.media-amazon.com/images/I/91rdTtLWAHL._AC_UL320_.jpg',
    url: 'https://amzn.to/4sUpfpk',
  },
  {
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    genre: 'Classic Literature',
    image: 'https://m.media-amazon.com/images/I/81IE8AwMvqL._AC_UY218_.jpg',
    url: 'https://amzn.to/4a8T6ll',
  },
  {
    title: 'Key to Living the Law of Attraction',
    author: 'Jack Canfield',
    genre: 'Self-Improvement',
    image: 'https://m.media-amazon.com/images/I/71xQR2x2cPL._AC_UY218_.jpg',
    url: 'https://amzn.to/4qan1jf',
  },
  {
    title: 'Beyond the Pleasure Principle: and Other Writings',
    author: 'Sigmund Freud',
    genre: 'Psychology',
    image: 'https://m.media-amazon.com/images/I/516yatdLH1L._AC_UY218_.jpg',
    url: 'https://amzn.to/4a2I1Dk',
  },
  {
    title: 'Meditations (150th Anniversary Collection Edition)',
    author: 'Marcus Aurelius',
    genre: 'Philosophy',
    image: 'https://m.media-amazon.com/images/I/712eLhPXOuL._AC_UY218_.jpg',
    url: 'https://amzn.to/4a21Udz',
  },
  {
    title: 'The Subtle Art of Not Giving a F*ck',
    author: 'Mark Manson',
    genre: 'Self-Help',
    image: 'https://m.media-amazon.com/images/I/71QKQ9mwV7L._AC_UY218_.jpg',
    url: 'https://amzn.to/3YOeYNy',
  },
  {
    title: 'Christian Standard Bible',
    author: 'Holman Bible Publishers',
    genre: 'Religion',
    image: 'https://m.media-amazon.com/images/I/81e3KXIiHPL._AC_CR0%2C0%2C0%2C0_SY315_.jpg',
    url: 'https://amzn.to/48EKXW4',
  },
  {
    title: "Precious Remedies Against Satan's Devices",
    author: 'Thomas Brooks',
    genre: 'Religion',
    image: 'https://m.media-amazon.com/images/I/718Z1HZzB0L._AC_UY218_.jpg',
    url: 'https://amzn.to/4pvyb24',
  },
  {
    title: 'Confessions',
    author: 'St. Augustine',
    genre: 'Religion',
    image: 'https://m.media-amazon.com/images/I/91B9ygxObFL._AC_UL320_.jpg',
    url: 'https://amzn.to/4sb1Xeq',
  },
  {
    title: 'The Books of Enoch Complete',
    author: 'Enoch',
    genre: 'Religion',
    image: 'https://m.media-amazon.com/images/I/71K-WHmBs9L._AC_UY218_.jpg',
    url: 'https://amzn.to/4998gHE',
  },
];
